#!/usr/bin/perl

# This program is part of Baidu MyHT Toolkit
# Date   : 2012-07-10 23:05 
# Author : hior<xiaozhiwen@baidu.com> 

use strict;
use warnings;

foreach (@ARGV) {
    if ($_ eq '-h' || $_ eq '--help') {
        print <<EOF
Add datetime prefix for raw mysql general log
Usage:
    mysql-log-prepare [-h|--help] [FILES]

For detail:
       perldoc mysql-log-prepare
EOF
;
        exit 1;
    }
}

unless (@ARGV) {
    push @ARGV, "<&=0";
}

my $buf = '';
my %HT = ();
foreach my $file (@ARGV) 
{
    my $t = '';
    open(FH, $file) or die "open file $file error: $!\n";
    while (<FH>) {

#        next until (/Query/|Execute);
        chomp;

        if (s/^.*?Connect\s+/Connect /) {
            s/\@[^\s]+/\@1.1.1.1/;
            $HT{$_}++;
            next;
        }

        next unless (s/^.*?(Query|Execute)//);
        
        s/\n|\s+/ /g;

        # in 
        s/IN\s*\([^)]+\)/IN (L,I,S,T)/ig;

		# for column = 1
        #s/\b\d+\b/1/g;
		# for table_0
        s/\d+\b/1/g;

        s/\b0x[0-9A-Fa-f]+\b/0x01/g;
        s/\\'|\\"|I'm//g;

        s/'[^']*?'/S/g;
        s/"[^"]*?"/S/g;

        s/\)\s*,\s*\(.+$/)/;
        s/\/\*.+\*\///;

        $HT{$_}++;
    }
    close(FH);
}

# sort reverse
foreach my $sql(sort { $HT{$b} <=> $HT{$a}} keys %HT) {
    printf "%d\t%s\n", $HT{$sql}, $sql;
}
exit 0;


# ############################################################################
# Documentation
# ############################################################################
=pod

=head1 NAME

mysql-log-prepare - Add datetime for each line 

=head1 SYNOPSIS

Usage: mysql-log-prepare [-h|--help] [FILES]

=over

=item Read from stdin:

mysql-log-prepare < mysql.log
cat mysql.log | mysql-log-prepare | less

=item Read from file list:

mysql-log-prepare mysql.log.20120101 mysql.log.20120102 | less

=head1 VERSION

mysql-log-prepare 1.0.0

=cut
